---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/opt/kibana/config/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: copy dashboard and importer
  copy:
    src={{item}}
    dest=/opt/{{item}}
  with_items:
    - kibana-ossecwazuh-dashboards.json
    - import_dashboards.py
  when: kibana_ossec-wazuh_dashboards

- name: import ossec-wazuh dashboards
  shell: python /opt/import_dashboards.py {{kibana_elasticsearch_url}} < /opt/kibana-ossecwazuh-dashboards.json
  when: kibana_ossec-wazuh_dashboards
